version: '3'
services:
  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    container_name: workplace
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ../../:/var/www/html
    depends_on:
      - php
    restart: always
    networks:
      - network
  redis:
    image: redis:latest
    command: redis-server --save 20 1 --loglevel warning --requirepass secret_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - network
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: default
      POSTGRES_DB: people_management
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - network
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    restart: always
    networks:
      - network
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: always
    networks:
      - network
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ../../:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: people_management
      DB_USERNAME: default
      DB_PASSWORD: secret
      CACHE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: secret_redis
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_DATABASE: your_mongodb_database_name
      MONGODB_USERNAME: your_mongodb_username
      MONGODB_PASSWORD: your_mongodb_password
    depends_on:
      - postgres
      - redis
      - mongo
    restart: always
  supervisor:
    build:
      context: ./supervisor
      dockerfile: Dockerfile
    volumes:
      - ./supervisor/conf:/etc/supervisor/conf.d
    depends_on:
      - php
    networks:
      - network
networks:
  network:
    driver: bridge